### ISSUE TITLE
where is the .go-msfdb.yaml file 

### ISSUE THREAD

**Issue by iamwlb** [vulsio/go-msfdb#41]
config file (default is $HOME/.go-msfdb.yaml)
but where is .go-msfdb.yaml

**Comment by MaineK00n** [comment]
By default, it will try to read the config in $HOME/.go-msfdb.yaml.
It does not generate $HOME/.go-msfdb.yaml.
https://github.com/vulsio/go-msfdb/blob/4a9759bd9f144d0b871c5450a20e2eefe8253ca1/commands/root.go#L88-L101

**Comment by shino** [comment]
This issue was closed because it has been inactive.
